openapi: "3.0.0"
info:
  description: "Skeleton Service for creating models and API interface for rest ws to give to clients"
  version: "0.0.1"
  title: "Model Service Skeleton API"
  contact:
    email: "arnoldmanyere@gmail.com"
tags:
  - name: "user"
    description: "User - dummy tag to initialise service"
#servers:
#  - url: http://localhost:8000/
#    description: "local host"

/notification/email:
  post:
    description: sending email notifications
    operationId: sendEmailNotification
    tags:
      - notificationService
    requestBody:
      content:
        application/json:
          schema:
            $ref: ./email.yml#/Email
      description:  Allows sending of email notification
      required: true
    responses:
      200:
        description: The Email Response object with email details and a ref ID
        content:
          application/json:
            schema:
              $ref: ./email-response.yml#/EmailResponse
      400:
        description: HTTP 400 Failed to send Email
        content:
          application/json:
            schema:
              $ref: ./errors/problem.yml#/Problem
      401:
        description: Unauthorized - The request requires user authentication
      403:
        description: Forbidden - The server understood the request, but is refusing it or
          the access is not allowed.
      404:
        description: Resource not found
      500:
        description: HTTP 500 Error Response
        content:
          application/json:
            schema:
              $ref: ./errors/problem.yml#/Problem

